### ISSUE TITLE
Provide an option to triggerAsync on already serialsied data

### ISSUE THREAD

**Issue by jackkettle** [pusher/pusher-http-dotnet#63]
We are encountering the issue of pusher messages being too large (over 10 kb) in our solution. As such to avoid this situation we need to check the size of the data before sending it. To do this we need to serialize the data ourself and check the length before sending the data. We are sending millions of messages per day so it would be nice if we could send a serialize json string to pusher instead of having an object. This way we could avoid having the expensive serialize operation having to happen twice per message.

public async Task<ITriggerResult> TriggerAsync(
  string[] channelNames,
  string eventName,
  string data
)

**Comment by elverkilde** [comment]
Instead of the solution proposed here, we have added a new option, which will throw an exception if the serialised size is over the limit. This is consistent with other SDKs, and hopefully provides the same benefits. You should use the default limit as described here:

https://github.com/pusher/pusher-http-dotnet#detecting-event-data-that-exceeds-the-10kb-threshold

Please give this a try. I am going to close this issue, but feel free to re-open if this does not resolve your issue.
